/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface VrMain {
    }
    interface VrRoot {
    }
    interface VrScene {
        "activeCollarID": string;
        "activeEnvironment": number;
        "environments": any[];
        "interactableItemList": any[];
        "resetScene": () => Promise<void>;
        "reviewEnabled": boolean;
        "showSplash": boolean;
        "socket": any;
        "userEnvironment": number;
    }
}
export interface VrSceneCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLVrSceneElement;
}
declare global {
    interface HTMLVrMainElement extends Components.VrMain, HTMLStencilElement {
    }
    var HTMLVrMainElement: {
        prototype: HTMLVrMainElement;
        new (): HTMLVrMainElement;
    };
    interface HTMLVrRootElement extends Components.VrRoot, HTMLStencilElement {
    }
    var HTMLVrRootElement: {
        prototype: HTMLVrRootElement;
        new (): HTMLVrRootElement;
    };
    interface HTMLVrSceneElement extends Components.VrScene, HTMLStencilElement {
    }
    var HTMLVrSceneElement: {
        prototype: HTMLVrSceneElement;
        new (): HTMLVrSceneElement;
    };
    interface HTMLElementTagNameMap {
        "vr-main": HTMLVrMainElement;
        "vr-root": HTMLVrRootElement;
        "vr-scene": HTMLVrSceneElement;
    }
}
declare namespace LocalJSX {
    interface VrMain {
    }
    interface VrRoot {
    }
    interface VrScene {
        "activeCollarID"?: string;
        "activeEnvironment"?: number;
        "environments"?: any[];
        "interactableItemList"?: any[];
        "onEnvironmentLoaded"?: (event: VrSceneCustomEvent<any>) => void;
        "onItemInteractedWith"?: (event: VrSceneCustomEvent<any>) => void;
        "onTeleportedEnvironment"?: (event: VrSceneCustomEvent<any>) => void;
        "reviewEnabled"?: boolean;
        "showSplash"?: boolean;
        "socket"?: any;
        "userEnvironment"?: number;
    }
    interface IntrinsicElements {
        "vr-main": VrMain;
        "vr-root": VrRoot;
        "vr-scene": VrScene;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "vr-main": LocalJSX.VrMain & JSXBase.HTMLAttributes<HTMLVrMainElement>;
            "vr-root": LocalJSX.VrRoot & JSXBase.HTMLAttributes<HTMLVrRootElement>;
            "vr-scene": LocalJSX.VrScene & JSXBase.HTMLAttributes<HTMLVrSceneElement>;
        }
    }
}
